spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: flight-service
          uri: http://localhost:8082
          predicates:
            - Path=/flights/**
        - id: ticket-service
          uri: http://localhost:8083
          predicates:
            - Path=/tickets/**
      default-filters:
        - AddRequestHeader=Global-Header, GatewayDemo
        - AddRequestHeader=X-Global-Header, GlobalValue
        - AddResponseHeader=X-Response-Time, {T(java.time.LocalDateTime).now()}
server:
  port: 8080
